---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: ghcr.io/dandyrow/podman-${MOLECULE-DISTRO:-ubuntu2204}-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
